version: 0.1.{build}
# environment variables
environment:
  # Don't report back to the mothership
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
configuration: Debug
platform: Any CPU
init:
- cmd: git config --global core.autocrlf true
before_build:
- cmd: appveyor-retry dotnet restore -v Minimal
- cmd: nuget restore
build:
  project: CoreCRM.sln
  verbosity: minimal
test_script:
- cmd: dotnet test CoreCRM.IntegrationTest
cache:
- '%USERPROFILE%\.nuget\packages'
deploy: off
